pull_request_rules:
  - name: Automatic merge for labelled pull requests
    conditions:
      - label=merge when ready
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
      label:
        remove:
          - merge when ready

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base=development
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
