# Programming language
language: java

before_install:
  # Install the tool to switch between JDK versions
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

script: mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -B -V

### Maven basic build ###
jobs:
  include:
    # 1. Test project against various JDKs
    - stage: Test against various JDKs
      name: Default JDK
      install: source ./install-jdk.sh --verbose
    - name: JDK 8 # LTS
      install: source ./install-jdk.sh --verbose --feature 11
    - name: JDK 11 # LTS
      install: source ./install-jdk.sh --verbose --feature 11
    - name: JDK 14 # Latest GA experimental
      install: source ./install-jdk.sh --verbose --feature 14
    - name: JDK 15 # Latest non-GA experimental
      install: source ./install-jdk.sh --verbose --feature 15
    # 2. Deploy
    - stage: deploy
      jdk: openjdk8 # Use the minimal supported version (this assures that no version-specific bytecode gets generated)
      if: repo = JarvisCraft/padla AND branch IN (master, development) AND type != pull_request
      deploy: source ./attempt-travis-deploy.sh

# Cached directories
cache:
  directories:
    - ~/.m2/repository # Maven repository
