name: Deploy release

on:
  push:
    tags: [ v* ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 8
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Import GPG signing key
        run: |
          echo -e "${{ secrets.CODE_SIGNING_GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Deploy snapshot
        env:
          CODE_SIGNING_GPG_KEY_ID: ${{ secrets.CODE_SIGNING_GPG_KEY_ID }}
          CODE_SIGNING_GPG_KEY_PASSPHRASE: ${{ secrets.CODE_SIGNING_GPG_KEY_PASSPHRASE }}
          SONATYPE_OSSRH_DEPLOYER: ${{ secrets.SONATYPE_OSSRH_DEPLOYER }}
          SONATYPE_OSSRH_TOKEN: ${{ secrets.SONATYPE_OSSRH_TOKEN }}
          GITHUB_PACKAGE_REGISTRY_DEPLOYER: JarvisCraft
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github-actions/scripts/maven_deploy.sh release
