name: Deploy snapshot

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Java 8 & Deployment credentials
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          server-id: 'sonatype-ossrh'
          server-username: ${{ secrets.SONATYPE_OSSRH_DEPLOYER }}
          server-password: ${{ secrets.SONATYPE_OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.CODE_SIGNING_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.CODE_SIGNING_GPG_KEY_PASSPHRASE }}

      - uses: jactions/maven-version@v1.0.0
        id: get_version

      - name: Deploy snapshot
        if: ${{ endsWith(steps.get_version.outputs.version, '-SNAPSHOT') }}
        run: mvn deploy -B -P build-extras,sign-artifacts
