name: Test

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16' ]

    name: Test with Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Cache Maven local repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn -B test
