name: Test

on: [ pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Java 17
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Run tests
        run: mvn -B test
