name: Test

# Only test (without creating JARs) pull-requests
on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test with Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17-ea'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B test
